version: '3.8'
services:
  mi_mysql:
    image: mysql:latest
    restart: always
    environment:
    - MYSQL_DATABASE=monfab
    - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
